services:
  bot:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - PRICE_THRESHOLD=${PRICE_THRESHOLD}
      - CHECK_INTERVAL=${CHECK_INTERVAL}
      - OWNER_ID=${OWNER_ID}
    restart: unless-stopped